/** Geometry is measured in the source image pixel space. */
export function containRect(width,height,boxWidth,boxHeight){const scale=Math.min(boxWidth/width,boxHeight/height);return{width:width*scale,height:height*scale,left:(boxWidth-width*scale)/2,top:(boxHeight-height*scale)/2,scale};}
export function imagePoint(clientX,clientY,rect,width,height){return{x:Math.round(Math.max(0,Math.min(width-1,(clientX-rect.left)/rect.width*width))),y:Math.round(Math.max(0,Math.min(height-1,(clientY-rect.top)/rect.height*height)))};}
export function normalizedRectangle(a,b){return{x1:Math.min(a.x,b.x),y1:Math.min(a.y,b.y),x2:Math.max(a.x,b.x),y2:Math.max(a.y,b.y)};}

const PALETTE=[['red','红色','#f05252'],['green','绿色','#45c878'],['blue','蓝色','#4f9bff'],['yellow','黄色','#ffd34e']];
const clone=value=>JSON.parse(JSON.stringify(value));
const newLayerId=()=>`annotation-layer-${crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
const validColor=value=>PALETTE.some(([key])=>key===value)?value:'red';
function initialLayers(initial){
  if(Array.isArray(initial?.annotationLayers))return clone(initial.annotationLayers).map(layer=>({id:layer.id||newLayerId(),color:validColor(layer.color),text:String(layer.text||''),marks:Array.isArray(layer.marks)?layer.marks:[]}));
  const groups=new Map();
  (initial?.annotations||[]).forEach((mark,index)=>{const id=mark.layerId||`legacy-${index}`;if(!groups.has(id))groups.set(id,{id:newLayerId(),color:validColor(mark.color),text:String(mark.text||''),marks:[]});groups.get(id).marks.push(mark);});
  return [...groups.values()];
}

export function openRegionEditor({mode='mask',sourceURL,sourceLabel='',initial=null,onConfirm,onClose,isLocked=()=>false}){
  // Legacy comment snapshots may still be opened from prompt history, but the
  // editor itself now exposes only the single mask workflow.
  if(mode!=='mask')throw new Error('当前只支持蒙版局部编辑');
  let drawings=clone(initial?.drawings||[]),layers=initialLayers(initial),redo=[],tool='smear',selected=initial?.selectedLayerId?layers.findIndex(layer=>layer.id===initial.selectedLayerId):Number(initial?.selected??-1),color='red',active=null,start=null;
  if(selected<0||selected>=layers.length)selected=layers.length?0:-1;
  if(selected>=0)color=layers[selected].color;
  let ready=false,busy=false,closed=false,feather=Number(initial?.feather||0),instruction=String(initial?.instruction||'');
  const root=document.createElement('div');root.className='qwen-region-modal';
  root.innerHTML=`<style>
.qwen-region-modal{position:fixed;inset:0;background:#080910dd;z-index:100100;display:flex;align-items:center;justify-content:center;color:#eee;font:13px/1.5 sans-serif}.qwen-region-modal *{box-sizing:border-box}.qwen-region-dialog{width:min(1240px,97vw);height:min(900px,95vh);background:#23242d;border:1px solid #515360;border-radius:12px;display:flex;flex-direction:column;overflow:hidden;box-shadow:0 16px 70px #0009}.qwen-region-header,.qwen-region-tools,.qwen-region-footer{display:flex;gap:8px;align-items:center;padding:9px 13px;flex-wrap:wrap;flex-shrink:0}.qwen-region-header{border-bottom:1px solid #41424e}.qwen-region-header strong{flex:1}.qwen-region-modal button{font:inherit;color:inherit;border:1px solid #555667;background:#30313f;border-radius:6px;min-height:32px;padding:5px 10px;cursor:pointer}.qwen-region-modal button.active,.qwen-region-modal .qwen-region-confirm{background:#7054ad;border-color:#b398e7}.qwen-region-modal button:disabled{opacity:.45;cursor:default}.qwen-region-body{display:flex;flex:1;min-height:0;padding:0 13px;gap:12px}.qwen-region-stage{position:relative;flex:1;min-width:0;min-height:0;background:#11121a;overflow:hidden;border-radius:7px}.qwen-region-picture{position:absolute;display:block;user-select:none;pointer-events:none}.qwen-region-canvas{position:absolute;touch-action:none;cursor:crosshair}.qwen-region-aside{width:310px;display:flex;flex-direction:column;gap:7px;min-height:0;overflow:auto}.qwen-region-layer-heading{display:flex;align-items:center;justify-content:space-between;gap:5px}.qwen-region-layer-heading .qwen-region-section-title{margin:0}.qwen-region-layer-actions{display:flex;gap:4px}.qwen-region-layer-actions button{min-height:26px;padding:2px 7px;font-size:11px}.qwen-region-list{display:flex;flex-direction:column;gap:5px;overflow:auto;min-height:20px;max-height:190px}.qwen-region-list button{width:100%;text-align:left;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.qwen-region-modal textarea{width:100%;min-height:90px;resize:vertical;background:#171821;color:#eee;border:1px solid #555667;border-radius:6px;padding:8px;font:inherit}.qwen-region-note{font-size:12px;color:#bbb}.qwen-region-error{color:#ffb5b5;flex:1}.qwen-region-footer{border-top:1px solid #41424e;margin-top:10px}.qwen-region-tools label{display:flex;align-items:center;gap:5px}.qwen-region-tools input[type=range]{width:90px;accent-color:#a58be0}.qwen-region-colors{display:flex;gap:5px}.qwen-region-color{width:25px;height:25px;min-height:25px!important;padding:0!important;border-radius:50%!important}.qwen-region-color.active{outline:2px solid white;outline-offset:2px}.qwen-region-section-title{font-size:12px;color:#bbb;margin-top:3px}@media(max-width:720px){.qwen-region-aside{width:245px}.qwen-region-dialog{height:96vh}.qwen-region-tools{padding:6px}}
</style><section class="qwen-region-dialog" role="dialog" aria-modal="true" aria-label="蒙版重绘"><header class="qwen-region-header"><strong></strong><button data-action="close" aria-label="关闭">关闭 Esc</button></header><div class="qwen-region-tools"></div><div class="qwen-region-body"><div class="qwen-region-stage"><img class="qwen-region-picture" draggable="false" alt="编辑源图"><canvas class="qwen-region-canvas"></canvas></div><aside class="qwen-region-aside"><div class="qwen-region-note">紫色涂抹为实际重绘范围；空心矩形框内也是重绘范围。彩色标注用于向模型说明位置，不会改变蒙版范围。每个图层可包含多笔标注。</div><div class="qwen-region-section-title">紫色涂抹区域的修改要求</div><textarea data-mask-instruction aria-label="紫色蒙版修改要求" placeholder="输入紫色涂抹区域要如何修改"></textarea><div class="qwen-region-layer-heading"><div class="qwen-region-section-title">彩色标注图层</div><div class="qwen-region-layer-actions"><button type="button" data-layer-add title="新建图层" aria-label="新建标注图层">＋</button><button type="button" data-layer-erase title="擦除当前图层的所有标注">擦除标注</button><button type="button" data-layer-delete title="删除当前图层">删除</button></div></div><div class="qwen-region-list"></div><div class="qwen-region-section-title" data-mark-label hidden>当前图层的修改要求</div><textarea data-mark-instruction aria-label="当前图层修改要求" placeholder="选择图层，输入该图层标注区域的修改内容" hidden></textarea></aside></div><footer class="qwen-region-footer"><span class="qwen-region-error" role="status"></span><button data-action="cancel">取消</button><button class="qwen-region-confirm" data-action="confirm">确认并填入</button></footer></section>`;
  document.body.append(root);
  const q=s=>root.querySelector(s),stage=q('.qwen-region-stage'),picture=q('img'),canvas=q('canvas'),ctx=canvas.getContext('2d'),raw=document.createElement('canvas'),rawCtx=raw.getContext('2d'),overlay=document.createElement('canvas'),overlayCtx=overlay.getContext('2d'),tools=q('.qwen-region-tools'),list=q('.qwen-region-list'),status=q('.qwen-region-error'),maskText=q('[data-mask-instruction]'),markText=q('[data-mark-instruction]'),layerAdd=q('[data-layer-add]'),layerErase=q('[data-layer-erase]'),layerDelete=q('[data-layer-delete]');
  q('strong').textContent=`蒙版重绘 · ${sourceLabel}`;maskText.value=instruction;
  const button=(label,callback,title=label)=>{const b=document.createElement('button');b.textContent=label;b.title=title;b.onclick=callback;tools.append(b);return b;};
  const toolButtons=[];
  for(const[name,label]of[['smear','涂抹'],['brush','画笔'],['rect','矩形框'],['eraser','橡皮擦']]){const b=button(label,()=>{tool=name;syncTools();});b.dataset.tool=name;toolButtons.push(b);}
  tools.append(document.createTextNode('颜色'));
  const swatches=document.createElement('div');swatches.className='qwen-region-colors';tools.append(swatches);
  const colorButtons=PALETTE.map(([key,label,value])=>{const b=document.createElement('button');b.className='qwen-region-color';b.type='button';b.title=label;b.setAttribute('aria-label',`${label}标注颜色`);b.style.background=value;b.dataset.color=key;b.onclick=()=>{if(busy||isLocked())return;color=key;if(selected>=0&&layers[selected].color!==key){remember();layers[selected].color=key;}syncTools();render();};swatches.append(b);return b;});
  let brushSize=36,undoButton,redoButton;
  function slider(label,min,max,value,update){const l=document.createElement('label'),input=document.createElement('input'),out=document.createElement('span');input.type='range';input.min=min;input.max=max;input.value=value;l.append(document.createTextNode(label),input,out);input.oninput=()=>{out.textContent=input.value+' px';update(Number(input.value));};tools.append(l);input.oninput();return input;}
  slider('笔刷',1,300,36,v=>brushSize=v);undoButton=button('撤销',undo);redoButton=button('重做',redoAction);button('清空',clearAll);slider('羽化',0,64,feather,v=>{feather=v;if(ready)render();});
  function syncTools(){toolButtons.forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));colorButtons.forEach(b=>b.classList.toggle('active',b.dataset.color===color));}
  syncTools();
  function markBounds(mark){if(mark.kind==='annotationRect')return{x1:mark.x1,y1:mark.y1,x2:mark.x2,y2:mark.y2};const xs=mark.points.map(p=>p.x),ys=mark.points.map(p=>p.y),pad=(mark.size||1)/2;return{x1:Math.min(...xs)-pad,y1:Math.min(...ys)-pad,x2:Math.max(...xs)+pad,y2:Math.max(...ys)+pad};}
  function maskBounds(){const data=rawCtx.getImageData(0,0,raw.width,raw.height).data;let x1=raw.width,y1=raw.height,x2=-1,y2=-1;for(let i=3,p=0;i<data.length;i+=4,p++){if(!data[i])continue;const x=p%raw.width,y=Math.floor(p/raw.width);if(x<x1)x1=x;if(x>x2)x2=x;if(y<y1)y1=y;if(y>y2)y2=y;}return x2<0?null:{x1,y1,x2:x2+1,y2:y2+1};}
  function boundsFor(s){if(s.kind==='rect'||s.kind==='maskRect')return{x1:s.x1,y1:s.y1,x2:s.x2,y2:s.y2};const xs=(s.points||[]).map(p=>p.x),ys=(s.points||[]).map(p=>p.y),pad=(s.size||1)/2;return xs.length?{x1:Math.min(...xs)-pad,y1:Math.min(...ys)-pad,x2:Math.max(...xs)+pad,y2:Math.max(...ys)+pad}:null;}
  function paintMask(c,s){if(s.kind==='clear'){c.clearRect(0,0,raw.width,raw.height);return;}c.save();c.globalCompositeOperation=s.erase?'destination-out':'source-over';c.fillStyle='white';c.strokeStyle='white';c.lineCap='round';c.lineJoin='round';c.lineWidth=s.size||1;if(s.kind==='rect'||s.kind==='maskRect')c.fillRect(s.x1,s.y1,s.x2-s.x1,s.y2-s.y1);else if(s.points?.length){c.beginPath();c.moveTo(s.points[0].x,s.points[0].y);for(const p of s.points.slice(1))c.lineTo(p.x,p.y);c.stroke();if(s.points.length===1){c.beginPath();c.arc(s.points[0].x,s.points[0].y,(s.size||1)/2,0,Math.PI*2);c.fill();}}c.restore();}
  function paintMark(c,m){const colorValue=PALETTE.find(x=>x[0]===m.color)?.[2]||'#f05252';c.save();c.strokeStyle=colorValue;c.lineWidth=Math.max(2,(m.size||4));c.lineCap='round';c.lineJoin='round';if(m.kind==='annotationRect'){c.strokeRect(m.x1,m.y1,m.x2-m.x1,m.y2-m.y1);}else if(m.points?.length){c.beginPath();c.moveTo(m.points[0].x,m.points[0].y);for(const p of m.points.slice(1))c.lineTo(p.x,p.y);if(m.points.length===1){c.beginPath();c.arc(m.points[0].x,m.points[0].y,Math.max(2,(m.size||4)/2),0,Math.PI*2);c.fillStyle=colorValue;c.fill();}else c.stroke();}c.restore();}
  function allMarks(){return layers.flatMap(layer=>layer.marks.map(mark=>({...mark,color:layer.color,text:layer.text,layerId:layer.id})));}
  function render(){if(!ready)return;ctx.clearRect(0,0,canvas.width,canvas.height);rawCtx.clearRect(0,0,raw.width,raw.height);overlayCtx.clearRect(0,0,overlay.width,overlay.height);drawings.forEach(s=>paintMask(rawCtx,s));if(active?.layer==='mask')paintMask(rawCtx,active);overlayCtx.drawImage(raw,0,0);overlayCtx.globalCompositeOperation='source-in';overlayCtx.fillStyle='#a56bffdd';overlayCtx.fillRect(0,0,overlay.width,overlay.height);overlayCtx.globalCompositeOperation='source-over';allMarks().forEach(m=>paintMark(overlayCtx,m));if(active?.layer==='annotation')paintMark(overlayCtx,{...active,color:layers[selected]?.color||color});ctx.drawImage(overlay,0,0);undoButton.disabled=busy||(!drawings.length&&!layers.some(layer=>layer.marks.length));redoButton.disabled=busy||!redo.length;renderList();}
  function renderList(){list.replaceChildren();layers.forEach((layer,i)=>{const b=document.createElement('button');b.classList.toggle('active',i===selected);b.style.borderLeft=`5px solid ${PALETTE.find(x=>x[0]===layer.color)?.[2]||'#fff'}`;b.textContent=`${i+1}. ${layer.text||'点击输入修改要求'}${layer.marks.length?` · ${layer.marks.length}笔`:''}`;b.disabled=busy||isLocked();b.onclick=()=>selectLayer(i);list.append(b);});const hasLayer=selected>=0&&selected<layers.length;layerErase.disabled=busy||isLocked()||!hasLayer||!layers[selected].marks.length;layerDelete.disabled=busy||isLocked()||!hasLayer;layerAdd.disabled=busy||isLocked();if(hasLayer){markText.hidden=false;q('[data-mark-label]').hidden=false;if(markText.value!==layers[selected].text)markText.value=layers[selected].text;}else{selected=-1;markText.hidden=true;q('[data-mark-label]').hidden=true;markText.value='';}}
  function selectLayer(index){if(busy||index<0||index>=layers.length)return;selected=index;color=layers[index].color;markText.hidden=false;q('[data-mark-label]').hidden=false;markText.value=layers[index].text||'';syncTools();renderList();render();}
  function addLayer(){if(busy||isLocked())return;remember();layers.push({id:newLayerId(),color,text:'',marks:[]});selectLayer(layers.length-1);markText.focus();}
  function eraseLayer(){if(busy||isLocked()||selected<0||!layers[selected]?.marks.length)return;remember();layers[selected].marks=[];render();}
  function deleteLayer(){if(busy||isLocked()||selected<0)return;remember();const next=Math.min(selected,layers.length-2);layers.splice(selected,1);selected=next;selectLayer(selected);render();}
  layerAdd.onclick=addLayer;layerErase.onclick=eraseLayer;layerDelete.onclick=deleteLayer;
  markText.oninput=()=>{if(selected>=0){layers[selected].text=markText.value;renderList();}};maskText.oninput=()=>{instruction=maskText.value;};
  function snapshot(){return{drawings:clone(drawings),annotationLayers:clone(layers),instruction,selectedLayerId:layers[selected]?.id||null};}
  function remember(){redo=[];undoStack.push(snapshot());if(undoStack.length>40)undoStack.shift();}
  const undoStack=[];
  function restore(s){drawings=s.drawings;layers=initialLayers(s);instruction=s.instruction;selected=s.selectedLayerId?layers.findIndex(layer=>layer.id===s.selectedLayerId):Number(s.selected??-1);if(selected<0||selected>=layers.length)selected=layers.length?0:-1;color=layers[selected]?.color||color;maskText.value=instruction;markText.value=selected>=0?layers[selected].text||'':'';render();syncTools();}
  function undo(){if(!undoStack.length)return;redo.push(snapshot());restore(undoStack.pop());}
  function redoAction(){if(!redo.length)return;undoStack.push(snapshot());restore(redo.pop());}
  function clearAll(){if(busy||isLocked()||(!drawings.length&&!layers.length))return;remember();drawings=[];layers=[];selected=-1;markText.value='';render();}
  function point(e){return imagePoint(e.clientX,e.clientY,canvas.getBoundingClientRect(),canvas.width,canvas.height);}
  canvas.onpointerdown=e=>{if(!ready||busy||isLocked()||e.button!==0)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);start=point(e);if(tool==='smear'||tool==='eraser')active={layer:'mask',kind:'stroke',erase:tool==='eraser',size:brushSize,points:[start]};else{if(selected<0)addLayer();const layer=layers[selected];color=layer.color;if(tool==='rect')active={layer:'annotation',kind:'annotationRect',color:layer.color,size:Math.max(4,brushSize/6),...normalizedRectangle(start,start)};else active={layer:'annotation',kind:'annotationStroke',color:layer.color,size:Math.max(4,brushSize/6),points:[start]};}render();};
  canvas.onpointermove=e=>{if(!active)return;const p=point(e);if(active.kind==='annotationRect'||active.kind==='rect'||active.kind==='maskRect')Object.assign(active,normalizedRectangle(start,p));else{const last=active.points.at(-1);if(Math.hypot(last.x-p.x,last.y-p.y)>=Math.max(1,active.size/8))active.points.push(p);}render();};
  canvas.onpointerup=e=>{if(!active)return;const p=point(e);if(active.kind==='annotationRect'||active.kind==='rect'||active.kind==='maskRect')Object.assign(active,normalizedRectangle(start,p));else{const last=active.points.at(-1);if(last.x!==p.x||last.y!==p.y)active.points.push(p);}const item=active;active=null;start=null;if((item.kind==='annotationRect'||item.kind==='rect'||item.kind==='maskRect')&&(item.x2-item.x1<1||item.y2-item.y1<1)){render();return;}remember();if(item.layer==='mask')drawings.push(item);else if(layers[selected])layers[selected].marks.push(item);render();if(item.layer==='annotation')markText.focus();};
  canvas.onpointercancel=()=>{active=null;start=null;render();};
  function fit(){if(!ready||closed)return;const r=containRect(canvas.width,canvas.height,stage.clientWidth,stage.clientHeight);for(const el of[picture,canvas])Object.assign(el.style,{width:r.width+'px',height:r.height+'px',left:r.left+'px',top:r.top+'px'});}
  const observer=new ResizeObserver(fit);observer.observe(stage);
  function close(){if(busy||closed)return;closed=true;observer.disconnect();document.removeEventListener('keydown',keydown,true);root.remove();canvas.width=canvas.height=raw.width=raw.height=overlay.width=overlay.height=1;onClose?.();}
  function keydown(e){if(e.key==='Escape'){e.stopPropagation();e.preventDefault();close();}else if(e.key==='Tab'){const els=[...root.querySelectorAll('button,input,textarea')].filter(el=>!el.disabled&&el.getClientRects().length),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
  document.addEventListener('keydown',keydown,true);q('[data-action=close]').onclick=close;q('[data-action=cancel]').onclick=close;
  const blob=c=>new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('无法生成辅助图片')),'image/png'));
  q('[data-action=confirm]').onclick=async()=>{if(!ready||busy||isLocked())return;status.textContent='';if(!instruction.trim()&&!layers.some(layer=>layer.marks.length&&layer.text.trim())){status.textContent='请填写涂抹区域或彩色标注图层的修改要求';maskText.focus();return;}const missingLayer=layers.findIndex(layer=>layer.marks.length&&!layer.text.trim());if(missingLayer>=0){status.textContent='请为每个有标注的图层填写修改要求';selectLayer(missingLayer);markText.focus();return;}
    try{render();const pixels=rawCtx.getImageData(0,0,raw.width,raw.height).data;let nonempty=false;for(let i=3;i<pixels.length;i+=4)if(pixels[i]){nonempty=true;break;}if(!nonempty&&!layers.some(layer=>layer.marks.some(mark=>mark.kind==='annotationRect'))){status.textContent='请先用紫色涂抹或画一个矩形框选定重绘范围';return;}
      busy=true;root.querySelectorAll('button,input,textarea').forEach(el=>el.disabled=true);status.textContent='正在准备…';
      const marks=allMarks();const maskCanvas=document.createElement('canvas');maskCanvas.width=canvas.width;maskCanvas.height=canvas.height;const mctx=maskCanvas.getContext('2d');mctx.fillStyle='black';mctx.fillRect(0,0,maskCanvas.width,maskCanvas.height);mctx.drawImage(raw,0,0);for(const a of marks)if(a.kind==='annotationRect'){mctx.fillStyle='white';mctx.fillRect(a.x1,a.y1,a.x2-a.x1,a.y2-a.y1);}
      const marked=document.createElement('canvas');marked.width=canvas.width;marked.height=canvas.height;const markedCtx=marked.getContext('2d');markedCtx.drawImage(picture,0,0);markedCtx.drawImage(overlay,0,0);
      const [mask,auxiliary]=await Promise.all([blob(maskCanvas),blob(marked)]);maskCanvas.width=maskCanvas.height=marked.width=marked.height=1;if(closed)return;
      const annotationLayers=layers.map(layer=>{const bounds=layer.marks.map(markBounds).filter(Boolean).reduce((all,b)=>all?{x1:Math.min(all.x1,b.x1),y1:Math.min(all.y1,b.y1),x2:Math.max(all.x2,b.x2),y2:Math.max(all.y2,b.y2)}:b,null);return{...clone(layer),bounds};});const annotationsOut=marks.map(m=>({...clone(m),bounds:markBounds(m)}));const accepted=await onConfirm({mode:'mask',width:canvas.width,height:canvas.height,drawings:clone(drawings),annotations:annotationsOut,annotationLayers,selectedLayerId:layers[selected]?.id||null,instruction:instruction.trim(),maskBounds:maskBounds(),feather,mask,auxiliary});
      busy=false;if(closed)return;if(accepted===false){root.querySelectorAll('button,input,textarea').forEach(el=>el.disabled=false);status.textContent='尚未应用，可继续修改';render();return;}close();
    }catch(error){busy=false;if(closed)return;root.querySelectorAll('button,input,textarea').forEach(el=>el.disabled=false);status.textContent=error?.message||'确认失败，请重试';render();}};
  picture.onload=()=>{if(closed)return;canvas.width=raw.width=overlay.width=picture.naturalWidth;canvas.height=raw.height=overlay.height=picture.naturalHeight;ready=true;fit();render();};picture.onerror=()=>{status.textContent='原图加载失败，请检查文件是否仍然存在';};picture.src=sourceURL;q('[data-action=close]').focus();
  return{close,destroy(){busy=false;close();}};
}
